export const IPC = {
    SHOW_PIP: "window:show-pip",
    SHOW_MAIN: "window:show-main",
    TIMER_START: "timer:start",
    TIMER_PAUSE: "timer:pause",
    TIMER_RESUME: "timer:resume",
    TIMER_STOP: "timer:stop",
    TIMER_TICK: "timer:tick",
    TIMER_GET_STATE: "timer:get-state",
    ACTIVITIES_GET_ALL: "activities:get-all",
    ACTIVITIES_ADD: "activities:add",
    ACTIVITIES_UPDATE: "activities:update",
    ACTIVITIES_DELETE: "activities:delete",
    PRESETS_GET_ALL: "presets:get-all",
    PRESETS_ADD: "presets:add",
    PRESETS_UPDATE: "presets:update",
    PRESETS_DELETE: "presets:delete",
    SETTINGS_GET: "settings:get",
    SETTINGS_UPDATE: "settings:update",
    STATS_GET_SUMMARY: "stats:get-summary",
};
